name: Java CI with Maven

on:
  push:
    branches: [ main, testStore-branch ]
  pull_request:
    branches: [ main, testStore-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn -B clean test

      - name: Test Summary
        if: always()
        run: |
          echo "Tests completed!"
          if [ -f target/surefire-reports/*.xml ]; then
            echo "Test results available in Surefire reports"
          fi